apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-bot-detection
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  allow:
  - 'apiexpert' 
  deny:
  - 'dummy-hacker'
plugin: bot-detection
